

spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/reservations
     username: resauser
     password: resapass
  jpa:
     hibernate:
         ddl-auto: create-drop
     show-sql: false
  flyway:
     enabled: false


server:
  port: 8080
  servlet:
    context-path: /reservations-api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    doc-expansion: none
    tags-sorter: alpha
  api-docs:
    path: /api-docs